############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Features"
url = "#features"
weight = 2

[[main]]
name = "Technology"
url = "#technology"
weight = 3

[[main]]
name = "Impact"
url = "#impact"
weight = 4

[[main]]
name = "About Us"
pageRef = "/about"
weight = 5

[[main]]
name = "Partners"
pageRef = "/partners"
weight = 6

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 7

# footer menu
[[footer]]
name = "About us"
pageRef = "/about"
weight = 1

[[footer]]
name = "Partners"
pageRef = "/partners"
weight = 2

[[footer]]
name = "Contact"
pageRef = "/contact"
weight = 3
